### ISSUE TITLE
Upgrading from 1.1.0-Alpha to 1.1.1 breaks builds becasue TablesDataModel does not exist

### ISSUE THREAD

**Issue by Eaglef90** [limbo-works/Limbo.Umbraco.Tables#22]
I was running the 1.1.0-Alpha with no issues and just upgraded the project to the 1.1.1 build but now in any Page.genereated.cs file that I have properties for Umbraco Tables I get the error

The type or namespace name 'TablesDataModel' does not exist in the namespace 'Limbo.Umbraco.Tables.Models' (are you missing an assembly reference?)

The code in the file is 

public virtual global::Limbo.Umbraco.Tables.Models.TablesDataModel UpcomingReleases => this.Value<global::Limbo.Umbraco.Tables.Models.TablesDataModel>(_publishedValueFallback, "upcomingReleases");

If I downgrade back to the alpha all works fine.

I did do a clean solution -> rebuild solution but that did not change anything.

Edit: I tried to go from alpha to 1.1.0 as well but same build error.

**Comment by abjerner** [comment]
Hi @Eaglef90 

`v1.1.0` contains a number of breaking changes, which was why these changes were released as part of a new major minor release instead of just a patch release. `v1.1.0` also has some additional breaking changes compared to `v1.1.0-alpha001`.

The changelog for `v1.1.0` mentions that some of the models (including `TablesDataModel`) were renamed, but I've updated the changelog a bit to better indicate that these are breaking changes:

https://github.com/limbo-works/Limbo.Umbraco.Tables/releases/tag/v1.1.0

The renaming will cause some issues with auto generated models, but you should be able to do a search and replace in your solution changing `TablesDataModel` to `TableModel`.

Hope that makes sense 😉

**Comment by Eaglef90** [comment]
I see the notes now, sorry about that. I was actually trying to find release notes for it before I opened the bug but I am not very familiar with github and could not find them. I know where they are now and will check them next time.
